### ISSUE TITLE
Uncaught TypeError: Cannot read property 'checked' of undefined

### ISSUE THREAD

**Issue by gaiterjones** [redchamps/login-as-customer-improvements#1]
When I set the opt-in checkbox enabled to no I get the above error when registering

`Uncaught TypeError: Cannot read property 'checked' of undefined`

This seems to break some of the registration js i.e. the submit button does not get disabled after clicking.

**Comment by rav-redchamps** [comment]
Hi @gaiterjones 

Thanks for reporting this.

We have fixed the problem locally and will be pushing it to the repository with in couple of hours from now along with some other changes/improvements.

**Comment by rav-redchamps** [comment]
Hi @gaiterjones 

Very sorry for the delay. The changes have been pushed live & you can update to version 1.0.1

I am closing this issue for now. Please feel free to reopen if you still see the problem.
